### ISSUE TITLE
Fetch new joke on button press

### ISSUE THREAD

**Issue by szhabolcs** [jonathanbossenger/devdadjokes#19]
I have shown the website to several people and the most requested feature was this, to have a button of some sorts that fetches a new joke.
One idea I had is to make the X (close) button fetch a new joke, with the following behavior:
- The user presses the X button
- He gets a prompt that says "Joke not saved" on the title bar and the following video as the content of the prompt: [video](https://www.youtube.com/watch?v=BLikP6BDH5w) which would be practical and funny at the same time 😂
- The options would be yes/no
- And if the user choses yes, a small animation plays and a new joke is fetched.

I don't know how we could implement the fetching, I know it can be done with an API call from JS, but it would be nicer to have it done with Laravel for consistency. (Small note, it would be best to fetch a new joke without refreshing the page)

**Comment by jonathanbossenger** [comment]
I have also thought about this, so thank's for logging it.

I am working on some back-end saving of jokes on #4, once that is implemented it will be possible to add an API to the app, which can return a new joke from the database, so I will keep this in mind.

Right now my focus is on #2, I managed to add "store joke dom to image" this weekend, so that will probably be next.

**Comment by jonathanbossenger** [comment]
This has been fixed in #25 

I didn't implement the Joke not saved video, will try and get that in a future release.
